{
    'name': 'Theme Trainin',
    'version': '1.0',
    'summary': 'Training Theme to get used to Odoo Theme Development',
    'description': 'Training Theme to get used to Odoo Theme Development',
    'category': 'Theme',
    'author': 'Auguria',
    'sequence': 3,
    'company': 'Auguria',
    'maintainer': 'Auguria',
    'depends': ['base', 'website', 'website_sale'],
    'data': [
        # 'views/template.xml',
        # 'views/odoo_theme.xml',
        'views/categories.xml',
        'views/clear_cart.xml',
        'views/contact_us.xml',
        'views/price_filter.xml',
        'views/shop1.xml',
        'views/layout.xml',
        'views/footer.xml',
        'views/header.xml',
        # 'views/page.xml',
        'views/snippets/amazing.xml',
        'views/snippets/arrivals_demo.xml',
        'views/snippets/new_arrivals.xml',
        'views/snippets/discount.xml',
        'views/snippets/main_banner.xml',
        'views/snippets/main_product.xml',
        'views/snippets/map.xml',
        'views/snippets/testimonial.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            '/theme_training/static/css/style.css',
            '/theme_training/static/css/animate.min.css',
            '/theme_training/static/css/owl.carousel.min.css',
            '/theme_training/static/css/owl.theme.default.min.css',
            '/theme_training/static/js/clear_cart.js',
            '/theme_training/static/js/custom.js',
            '/theme_training/static/js/new_arrivals.js',
            '/theme_training/static/js/owl.carousel.js',
            '/theme_training/static/js/owl.carousel.min.js',
            '/theme_training/static/js/price_filter.js',
        ],
    },
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
